### ISSUE TITLE
Notify people of rent partners at daily reset

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/auctioneer#20]
- subscribe command
- unsubscribe command
- at reset time, send a DM to subscribers with rent info

**Comment by rpherbig** [comment]
Or does an admin subscribe a CHANNEL and we post there?

**Comment by jackson-byrd** [comment]
With the introduction of Global Monitor this is pretty much obsolete.  However I am still looking at implementing #1

**Comment by rpherbig** [comment]
Makes sense to me
